### ISSUE TITLE
Cursor not in "Block" shape when starting VScode

### ISSUE THREAD

**Issue by badcodecat** [jasonwilliams/vscode-helix#1]
When reloading or starting VS Code, the cursor is in the "I-Beam" shape.
Going into insert mode and back to normal still works and changes the cursor into block shape.

**Comment by jasonwilliams** [comment]
Thanks for raising, will take a look. Feel free to raise any more issues if you come across some. It’s very alpha so will have a lot missing. Selections are not implemented yet

**Comment by badcodecat** [comment]
I'm rather new to helix in general so I probably won't be able to understand what's user error and actual error, but if I spot anything I'll try to let you know.

**Comment by jasonwilliams** [comment]
This is fixed in https://github.com/jasonwilliams/vscode-helix/commit/6c0548c1bbae08216a59368293ee765f5ae96f08 but not released yet

**Comment by jasonwilliams** [comment]
Released
