### ISSUE TITLE
Moving Left and Right Leaves a Selection that Lags Behind the Cursor

### ISSUE THREAD

**Issue by zicklag** [jasonwilliams/vscode-helix#10]
Hey there!

When enabling this plugin I run into an issue where moving left and right seems to leave a selection behind the cursor, such that when I insert, it actually replaces the previous character first, if I was moving right.

The expected behavior would be that only the cursor moves when pressing `j` or `l`, without selecting any text.

Downgrading to version `0.4.0` seems to fix that issue, at the expense of selection shortcuts like `wd` to delete a word don't work anymore.

**Comment by jasonwilliams** [comment]
Is this still happening on the latest version? 0.5.3?

**Comment by jasonwilliams** [comment]
Closing due to activity
