### ISSUE TITLE
Make compatible with https://vscode.dev/

### ISSUE THREAD

**Issue by David-Else** [jasonwilliams/vscode-helix#12]
Right now it says 'The 'Helix For VS Code' extension is not available in Visual Studio Code for the Web' and links to https://code.visualstudio.com/docs/editor/vscode-web#_extensions to explain, and https://code.visualstudio.com/api/extension-guides/web-extensions to add support. Cheers!

**Comment by jasonwilliams** [comment]
Hi David

I've released https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.5.7 which should work on the web, let me know if it doesn't

**Comment by David-Else** [comment]
Brilliant, thanks, works great!
