### ISSUE TITLE
Entering insert mode with 'i' does not clear the selection

### ISSUE THREAD

**Issue by HesamR** [jasonwilliams/vscode-helix#14]
if you have something selected in normal mode or visual mode and press 'i' to enter insert mode it keep the selection active which if I'm not mistaken is not helix behavior.

version reported in vscode : 5.5.0

**Comment by jasonwilliams** [comment]
I don't understand what you mean @HesamR can you show me a screenshot or a recording? When i select something in Helix and press I i still get the selection

**Comment by HesamR** [comment]
helix does keep the selection active in insert mode but when type it does not replace and delete the selection 

https://github.com/jasonwilliams/vscode-helix/assets/18302053/9b25f4dd-9b9b-4536-ba4c-3a93c73e2e4e

https://github.com/jasonwilliams/vscode-helix/assets/18302053/3bea556d-008d-4f4d-89d3-926b3705d1c1

**Comment by JackWolfard** [comment]
I also have this issue. The behavior is similar to `change_selection` which by default is `c`. I expect `insert_mode` which by default is `i` to insert before selection without any deletion.

**Comment by jasonwilliams** [comment]
Hmm this one is tricky, I don't know if there's a solution. If you highlight text in code and type it will replace the selection, its a core VSCode thing, I don't think that behaviour can be changed with extensions. The only option would be to try and remove the selection when you hit "i"

**Comment by jasonwilliams** [comment]
I think I’m going to try removing selections on “I”. This won’t match Helix’s UX but it will prevent the bug @JackWolfard is showing. How often do people go into insert mode but keep the selection alive, is this a common use case?

**Comment by HesamR** [comment]
I don't think so. I been using helix for 2 years as daily driver and I never noticed it keep the selection when you enter insert mode.

**Comment by jasonwilliams** [comment]
So this has been fixed but I've realised it should be inserting _before_ the selection regardless of where the cursor is and 'a' should always insert after the selection. 

I'd be keen for some contributions to this as to help out, this should be a good first issue if either of you wanted to take it
