### ISSUE TITLE
Move left(use H) or right(use L) to highlight the same character

### ISSUE THREAD

**Issue by linglingqi007** [jasonwilliams/vscode-helix#15]
<img width="501" alt="image" src="https://github.com/jasonwilliams/vscode-helix/assets/6560524/6b4225fb-00f2-47d3-80ab-768666708810">

Use the arrow keys, it's fine.

**Comment by jasonwilliams** [comment]
Can you give more detail or show a video please?

**Comment by linglingqi007** [comment]
> Can you give more detail or show a video please?

![Kapture 2024-01-29 at 15 06 01](https://github.com/jasonwilliams/vscode-helix/assets/6560524/16a2c88b-c963-4122-ae97-afe25a21f8fa)

**Comment by jasonwilliams** [comment]
Ah I see thanks for pointing this out, this was initally in there to support Visual mode, but if you're not in visual mode it shouldn't be trying to highlight at all. This can be fixed to just call normal move left/right when in Normal mode.
