### ISSUE TITLE
Missing upper/lowercase selected keybinding

### ISSUE THREAD

**Issue by chapmandu** [jasonwilliams/vscode-helix#17]
![image](https://github.com/jasonwilliams/vscode-helix/assets/1092563/04938ba8-a9f9-4179-9bf3-350be5203342)

On Linux `switch_to_uppercase` is `Shift + backtick`

**Comment by jasonwilliams** [comment]
Fixed in https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.6.1
