### ISSUE TITLE
Replace characters

### ISSUE THREAD

**Issue by beeb** [jasonwilliams/vscode-helix#19]
First of all, thanks for the great work you're doing with this extension! I follow the releases and you're doing great!

I noticed something today when trying to replace a single char:

- Move cursor in normal mode over a character
- Hit `c` to replace the character
- Extension immediately enters `insert` mode before the character, without first deleting it.

In helix, this keybind would remove the selection before entering insert mode.

When multiple characters are selected in normal mode, there is likewise a problem where only the last `n-1` characters are removed (when hitting  `c`) before entering insert mode.

**Comment by jasonwilliams** [comment]
Thanks for the kind words, this should be fixed in https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.6.2

**Comment by beeb** [comment]
Thanks for the fix!
