### ISSUE TITLE
Ctrl-A does not work outside of editor when in Normal mode

### ISSUE THREAD

**Issue by chapmandu** [jasonwilliams/vscode-helix#21]
![image](https://github.com/jasonwilliams/vscode-helix/assets/1092563/fbdbc3fc-e8d1-405d-8713-23cc03a177ac)

Using Ctrl-A should select existing search term. It works as expected when using Insert mode, but not in Normal mode.

**Comment by jasonwilliams** [comment]
This should be fixed in release https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.6.2
