### ISSUE TITLE
Making the extension available in open vsx?

### ISSUE THREAD

**Issue by Ramton03** [jasonwilliams/vscode-helix#24]
Hello,
Wanted to try helix keybinds in vscodium but only could find dance.Is it possible to publish it to [open-vsx](https://open-vsx.org/)?

**Comment by jasonwilliams** [comment]
I'll look into this

**Comment by jasonwilliams** [comment]
I'm not verified [yet](https://github.com/EclipseFdn/open-vsx.org/issues/2518), but here you go:
https://open-vsx.org/extension/jasew/vscode-helix-emulation

**Comment by jobukkit** [comment]
> I'm not verified [yet](https://github.com/EclipseFdn/open-vsx.org/issues/2518), but here you go: https://open-vsx.org/extension/jasew/vscode-helix-emulation

This link should be in the README next to the Visual Studio Marketplace link.

**Comment by jasonwilliams** [comment]
@jobukkit if you have capacity? Feel free to do a PR rectifying this
