### ISSUE TITLE
w/b doesn't select the word

### ISSUE THREAD

**Issue by beeb** [jasonwilliams/vscode-helix#7]
I noticed today that w/b does not select the word, unlike what helix does. As such, `wd` does not delete the next word.

**Comment by jasonwilliams** [comment]
This has been fixed in https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.4.1

**Comment by jasonwilliams** [comment]
I think it may need more work so the character is sitting on the last letter and not past the word, but let me know if this helps with your issue

**Comment by beeb** [comment]
Looks fine to me, not sure what the implications are of having the cursor past the word but `wd` works as expected. Thanks for the fix!
