### ISSUE TITLE
Custom keybind for ESC doesn't exit insert mode

### ISSUE THREAD

**Issue by beeb** [jasonwilliams/vscode-helix#8]
I have applied a modification to my keyboard layout (on ubuntu via `xkb-options` set to `['caps:escape_shifted_capslock']`) so that the caps lock key effectively acts as the ESC key. However, when I hit this key while in INSERT mode, the extension does not revert to NORMAL mode.

**Comment by jasonwilliams** [comment]
I have done the same thing, except on windows, and ESC is definitely returning to normal mode for me from insert. Are you seeing it still say `INS` at the bottom?

I can't reproduce this issue

**Comment by beeb** [comment]
It seems to be a VSCode issue, found this: https://stackoverflow.com/a/50875402. No action required here, except maybe if you want to document this.
