### ISSUE TITLE
Missing fundamental keybindings 

### ISSUE THREAD

**Issue by chapmandu** [jasonwilliams/vscode-helix#9]
Hey Jason,

Great work getting this project underway. If I'm not mistaken, there are some fundamental commands that I've noticed aren't present in normal mode.

```
y = yank
p = paste
u = undo
> = indent
< = outdent
```

There may be more,  but I'm still getting up to speed with Helix..
TIA

**Comment by jasonwilliams** [comment]
Undo should be supported but the rest need adding, thanks for raising

**Comment by jasonwilliams** [comment]
indent and outdent are added in the latest release

**Comment by jasonwilliams** [comment]
Closing this as all those features are either added or partially added
https://github.com/jasonwilliams/vscode-helix/releases/tag/v0.6.0
